name: DebtTracker
options:
  bundleIdPrefix: tarchenko
  deploymentTarget:
    iOS: 17.6
  usesTabs: false
  tabWidth: 4
  indentWidth: 4
  
targets:
  DebtTracker:
    type: application
    platform: iOS
    sources:
      - path: DebtTracker
    preBuildScripts:
      - name: Run SwiftFormat
        script: |
          export PATH="$PATH:/usr/local/bin:/opt/homebrew/bin"
          if which swiftformat >/dev/null; then
            swiftformat "$SRCROOT"
          else
            echo "error: SwiftFormat not installed. Please run: brew install swiftformat"
            exit 1
          fi
        outputFiles: []
        basedOnDependencyAnalysis: false
      - name: Run SwiftLint
        script: |
          export PATH="$PATH:/usr/local/bin:/opt/homebrew/bin"
          if which swiftlint >/dev/null; then
            swiftlint
          else
            echo "error: SwiftLint not installed. Please run: brew install swiftlint"
            exit 1
          fi
        outputFiles: []
        basedOnDependencyAnalysis: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: tarchenko.DebtTracker
        INFOPLIST_FILE: DebtTracker/Presentation/Common/Resources/Info.plist
        SWIFT_VERSION: 6.0
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
    info:
      path: DebtTracker/Presentation/Common/Resources/Info.plist
      properties:
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UILaunchStoryboardName: LaunchScreen
    dependencies:
      - package: SnapKit
    scheme:
      testTargets:
        - DebtTrackerTests
        
  DebtTrackerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: DebtTrackerTests
    dependencies:
      - target: DebtTracker
    settings:
      base:
        BUNDLE_LOADER: $(TEST_HOST)
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/DebtTracker.app/DebtTracker
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: tarchenko.DebtTrackerTests
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        
packages:
  SnapKit:
    url: https://github.com/SnapKit/SnapKit
    exactVersion: 5.7.1

