name: Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Run Unit Tests
    runs-on: macos-15
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_16.2.app
    
    - name: Install dependencies
      run: |
        brew install xcodegen
        brew install swiftlint
        brew install swiftformat
        
    - name: Generate Xcode project
      run: xcodegen generate
      
    - name: Build and Test
      run: |
        xcodebuild test \
          -scheme DebtTracker \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
          -enableCodeCoverage YES \
          -resultBundlePath TestResults \
          | xcpretty && exit ${PIPESTATUS[0]}
          
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: TestResults.xcresult
